### ISSUE TITLE
Cannot compile on lubuntu 13.04 my project

### ISSUE THREAD

**Issue by Hronom** [texus/TGUI#15]
Cannot compile my project on lubuntu 13.04 on latest commit: ae80e7dfbdbdf46d9b604766ab6a77e0a60442df recive this error:

```
libtgui.so: undefined reference to `tgui::SharedWidgetPtr<tgui::Widget>::operator->() const'
```

Revert to commit 7c02748050a9a482505da97117aad657a940a369 and all compiles ok!
My gcc 4.7.3 x86
